services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: certonly --dry-run --webroot -w /var/www/certbot --force-renewal --email chris@christaylordeveloper.co.uk -d editions.christaylordeveloper.co.uk --agree-tos --no-eff-email

volumes:
  certbot_www:
  certbot_conf:
