services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./acme-challenge.conf:/etc/nginx/conf.d/acme-challenge.conf
      - certbot_www:/var/www/html
      - certbot_conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/html
      - certbot_conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email chris@christaylordeveloper.co.uk --agree-tos --no-eff-email --force-renewal -d editions.christaylordeveloper.co.uk

volumes:
  certbot_www:
  certbot_conf:
