server {
  listen 80;
  server_name editions.christaylordeveloper.co.uk;

  location /.well-known/acme-challenge/ {
    root /var/www/html;
  }

  location / {
    rewrite ^ https://$host$request_uri? permanent;
  }
}

server {
  listen 443;
  server_name editions.christaylordeveloper.co.uk;

  ssl_certificate     /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/privkey.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
  }
}
