server {
  listen 80;
  server_name editions.christaylordeveloper.co.uk;

  location ~ /.well-known/acme-challenge/ {
    add_header X-Chris-Debug "In acme challenge" always;
    root /var/www/certbot;
  }

  location / {
    add_header X-Chris-Debug "In http to https rewrite" always;
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443;
  server_name editions.christaylordeveloper.co.uk;

  add_header X-Chris-Debug "In https server" always;

  ssl_certificate     /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/privkey.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
  }
}
