server {
  listen 80;
  server_name editions.christaylordeveloper.co.uk;

  location ~ /.well-known/acme-challenge/ {
    add_header X-Chris-Debug "In acme http challenge" always;
    root /var/www/certbot;
  }

  add_header X-Chris-Debug "In http to https return" always;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name editions.christaylordeveloper.co.uk;
  add_header X-Chris-Debug "In https server" always;

  ssl_certificate     /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/editions.christaylordeveloper.co.uk/privkey.pem;

  root /usr/share/nginx/html;
  index index.html index.htm;

  # For renewals
  location ~ /.well-known/acme-challenge/ {
    add_header X-Chris-Debug "In acme https challenge" always;
    root /var/www/certbot;
  }
}
